language: groovy
jdk:
- oraclejdk7
branches:
  only:
  - master
before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- "~/install_gvm.sh"
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- GRAILS_VERSION=`grep '^\s*app.grails.version' application.properties | sed -e 's/^\s*app\.grails\.version=//g'
  | tr -d "\r"`
- echo "GRAILS_VERSION:$GRAILS_VERSION"
- gvm install grails $GRAILS_VERSION || true
before_script:
- GRAILS_VERSION_NUMBER=`echo $GRAILS_VERSION | sed -e 's/\.[0-9]*$//g' -e 's/\.//g'`
- echo "GRAILS_VERSION_NUMBER:$GRAILS_VERSION_NUMBER"
- GRAILS_SETTINGS_FILE="travis_grails_settings_new.groovy"
- if [ "$GRAILS_VERSION_NUMBER" -lt "23" ]; then GRAILS_SETTINGS_FILE="travis_grails_settings_old.groovy";
  fi;
- echo "GRAILS_SETTINGS_FILE:$GRAILS_SETTINGS_FILE"
- mkdir -p ~/.grails; wget -q -O ~/.grails/settings.groovy https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/$GRAILS_SETTINGS_FILE
- MAVEN_REPO="ala-repo-snapshot"
- grep '^\s*app\.version=' ./application.properties | grep -q "\-SNAPSHOT"; if [ "$?"
  = "1" ]; then MAVEN_REPO="ala-repo-release"; fi;
- echo "MAVEN_REPO:$MAVEN_REPO"
script:
- grails clean && grails refresh-dependencies --non-interactive && grails prod war
  --non-interactive && grails prod maven-install --non-interactive
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grails prod maven-deploy
  --repository=$MAVEN_REPO --non-interactive'
env:
  global:
  - secure: R9ThRet54Ev1xhPuvJLisMqGmNIBtoIBtvd6XX+uUT9qsM0Ak+HdlBGlosKYP5XR/pWP9ApLm1p7/o5dFXXZlBf+yMiNhWx3GWd+4aYu8rFkEas9ZBl90EJ+w/7Fvj5sT2JRMqbX31Z/XcKSH2msKT/+YRfTUa5GEoFg8gOtUfg=
  - secure: Sg9xYSV3TZpyDe/Q5cenvmbPKmBadLRXBzsEkepJyxk2LEXPOBfDFFJG/nAmE3rxqJA4PvorxXsMXd5C1+IosJnmZ2YsFYjLJ3viNnSYW0zAyTyy4uXckoLWBZWPx+EdY8EQJnJio9w/0+uaOT7ZotP8QkemeUhJ+TVAZFfUFv0=
